[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs", "npm"]

[phases.install]
cmds = [
  "composer install --no-scripts --prefer-dist --optimize-autoloader",
  "npm ci"
]

[start]
cmd = 'bash -c "php bin/console cache:clear --env=prod && php bin/console cache:warmup --env=prod && mkdir -p var/sessions var/log && chmod -R 777 var/cache var/sessions var/log && php -S 0.0.0.0:$PORT -t public"'